version: '3.8'

services:
  app:
    container_name: spoon-ui
    build:
      context: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next